apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      emptyDir: {}

  initContainers:
    - name: git-clone
      image: alpine/git
      command:
        - sh
        - -c
        - |
          git clone https://github.com/parallelism623/lk8s.git /repo
          cp -r /repo/* /html
      volumeMounts:
        - name: html
          mountPath: /html