apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   
  storageClassName: ""                  
  csi:
    driver: disk.csi.azure.com
    volumeHandle: ""
    fsType: ext4