server {
    listen 80;
    server_name localhost;

    location / {
        return 200 "HTTP OK\n";
        add_header Content-Type text/plain;
    }
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        return 200 "HTTPS OK\n";
        add_header Content-Type text/plain;
    }
}