apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      imagePullSecrets:
      - name: anhhieu623-dockerhub-secret
      containers:
      - name: nodejs
        image: anhhieu623/kubia:v1
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080

          