apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: container-1
    image: this-image-does-not-exist:latest
    imagePullPolicy: Always
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo post-start hook container-1"]
  - name: container-2
    image: nginx:latest