apiVersion: v1
kind: Pod
metadata:
  name: test-pull-time
spec:
  containers:
  - name: container-1
    image: tensorflow/tensorflow:latest-gpu  # image rất nặng ~3GB
    imagePullPolicy: Always
  - name: container-2
    image: nginx:latest  # image nhẹ, pull nhanh