apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
spec:
  containers:
  - image: busybox
    name: limited-container
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    resources:
      limits:
        cpu: 1
        memory: "50Mi"