apiVersion: v1
kind: Pod
metadata:
  name: debug-box
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - name: debug-box
      image: ubuntu:22.04
      command: ["sleep", "infinity"]